"""The PDF reading path, checked for portability and for every refusal.

Phase 1 item E replaced a macOS-only renderer with a portable one, so these
checks are written against the things that break when a renderer changes:

* **the bounds still bound.** Input size, page count, pixels and encoded size
  each refuse before the work, not after it;
* **a refusal is still a refusal.** Malformed, encrypted, empty and cancelled
  documents raise rather than yielding a blank page a later stage would read as
  "the scan said nothing";
* **the page is not silently reoriented.** PDFium's page size already accounts
  for `/Rotate` and the Quartz path's crop box does not. Applying the wrong one
  turns an upright page sideways, and only a rotated fixture catches it;
* **the PNG is a real PNG.** It is encoded here from raw scanlines with the
  standard library, so its structure is asserted rather than assumed.

Every PDF here is built in memory by `minimal_pdf`, so the suite is hermetic and
commits no fixtures. The C07 scan is used only where a real scanned document is
the point, and skipped when absent.

    python -m unittest backend.coordinator.test_pdfrender
"""

from __future__ import annotations

import pathlib
import struct
import unittest
import zlib
from unittest.mock import patch

from backend.coordinator import pdfrender

SCAN_FIXTURE = (pathlib.Path(__file__).resolve().parents[2]
                / "fixtures/c07/documents/inspection-report-scan.pdf")


def minimal_pdf(pages: int = 1, width: int = 612, height: int = 792,
                rotate: int = 0) -> bytes:
    """A valid, blank PDF with the requested page geometry.

    Hand-built rather than generated by a library: the suite must be able to ask
    for a rotated page, forty pages or a zero-size box without depending on the
    very renderer under test to produce the input.
    """
    objects = ["1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"]
    kids = " ".join(f"{3 + i} 0 R" for i in range(pages))
    objects.append(f"2 0 obj\n<< /Type /Pages /Count {pages} "
                   f"/Kids [{kids}] >>\nendobj\n")
    for index in range(pages):
        objects.append(
            f"{3 + index} 0 obj\n<< /Type /Page /Parent 2 0 R "
            f"/MediaBox [0 0 {width} {height}] /Rotate {rotate} >>\nendobj\n")
    out, offsets = "%PDF-1.4\n", []
    for obj in objects:
        offsets.append(len(out))
        out += obj
    start = len(out)
    out += f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n"
    out += (f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{start}\n%%EOF\n")
    return out.encode("latin-1")



def text_pdf(pages) -> bytes:
    """A valid PDF whose pages carry a real text layer, or none.

    Each item is the text for one page, drawn with the standard Helvetica font;
    `None` gives a page with no text layer at all, which is what a scanned page
    looks like to a text reader. Hand-built for the same reason as
    `minimal_pdf`: the reader under test must not produce its own input.
    """
    count = len(pages)
    objects = ["<< /Type /Catalog /Pages 2 0 R >>",
               "<< /Type /Pages /Count {count} /Kids [{kids}] >>",
               "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]
    kids = []
    for text in pages:
        page_number = len(objects) + 1
        kids.append(f"{page_number} 0 R")
        if text is None:
            objects.append("<< /Type /Page /Parent 2 0 R "
                           "/MediaBox [0 0 612 792] >>")
            continue
        escaped = (text.replace("\\", "\\\\").replace("(", "\\(")
                   .replace(")", "\\)"))
        stream = f"BT /F1 12 Tf 72 720 Td ({escaped}) Tj ET"
        objects.append(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
                       f"/Resources << /Font << /F1 3 0 R >> >> "
                       f"/Contents {page_number + 1} 0 R >>")
        objects.append(f"<< /Length {len(stream)} >>\nstream\n{stream}\nendstream")
    objects[1] = objects[1].format(count=count, kids=" ".join(kids))
    out, offsets = "%PDF-1.4\n", []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n{body}\nendobj\n"
    start = len(out)
    out += f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n"
    out += (f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{start}\n%%EOF\n")
    return out.encode("latin-1")

def read_png(blob: bytes) -> dict:
    """Decode enough of a PNG to prove it is one, using only the stdlib.

    Chunk lengths and CRCs are verified, so a structurally broken image fails
    here instead of at whatever reads it next.
    """
    if not blob.startswith(b"\x89PNG\r\n\x1a\n"):
        raise AssertionError("not a PNG")
    offset, chunks, order = 8, {}, []
    while offset < len(blob):
        (length,) = struct.unpack(">I", blob[offset:offset + 4])
        kind = blob[offset + 4:offset + 8]
        payload = blob[offset + 8:offset + 8 + length]
        (crc,) = struct.unpack(">I", blob[offset + 8 + length:offset + 12 + length])
        if crc != zlib.crc32(kind + payload) & 0xFFFFFFFF:
            raise AssertionError(f"bad CRC on {kind!r}")
        chunks.setdefault(kind, b"")
        chunks[kind] += payload
        order.append(kind)
        offset += 12 + length
    width, height, depth, colour, compression, filt, interlace = struct.unpack(
        ">IIBBBBB", chunks[b"IHDR"])
    raw = zlib.decompress(chunks[b"IDAT"])
    stride = width * 3
    rows, filters = [], []
    for index in range(height):
        start = index * (stride + 1)
        filters.append(raw[start])
        rows.append(raw[start + 1:start + 1 + stride])
    return {"width": width, "height": height, "depth": depth, "colour": colour,
            "compression": compression, "filter": filt, "interlace": interlace,
            "rows": rows, "filters": filters, "order": order}


class PngEncoding(unittest.TestCase):
    """The encoder, on its own. No PDF involved."""

    def test_it_writes_a_structurally_valid_eight_bit_rgb_png(self):
        rows = [bytes([255, 0, 0] * 3), bytes([0, 255, 0] * 3)]
        image = read_png(pdfrender.encode_png(3, 2, rows))
        self.assertEqual((image["width"], image["height"]), (3, 2))
        self.assertEqual(image["depth"], 8)
        self.assertEqual(image["colour"], 2, "colour type 2 is RGB")
        self.assertEqual(image["interlace"], 0)
        self.assertEqual(image["rows"], rows)

    def test_every_scanline_uses_the_none_filter(self):
        """Filter 0 means the bytes depend on the pixels and nothing else."""
        image = read_png(pdfrender.encode_png(2, 3, [b"\x01\x02\x03" * 2] * 3))
        self.assertEqual(set(image["filters"]), {0})

    def test_the_chunks_appear_in_the_required_order(self):
        image = read_png(pdfrender.encode_png(1, 1, [b"\x00\x00\x00"]))
        self.assertEqual(image["order"], [b"IHDR", b"IDAT", b"IEND"])

    def test_the_same_pixels_encode_to_the_same_bytes(self):
        rows = [bytes(range(9))] * 4
        self.assertEqual(pdfrender.encode_png(3, 4, rows),
                         pdfrender.encode_png(3, 4, rows))

    def test_a_wrong_row_count_is_refused_not_padded(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            pdfrender.encode_png(2, 3, [b"\x00" * 6])
        self.assertEqual(caught.exception.code, "encode")

    def test_a_malformed_scanline_is_refused_not_truncated(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            pdfrender.encode_png(2, 1, [b"\x00" * 5])
        self.assertEqual(caught.exception.code, "encode")


class PortableRenderer(unittest.TestCase):
    """The pypdfium2 backend, named explicitly so the test says what it ran."""

    def setUp(self):
        state = pdfrender._pdfium_probe()
        if not state["available"]:
            self.skipTest(state["detail"])

    def render(self, data, **kwargs):
        kwargs.setdefault("backend", pdfrender.PDFIUM)
        return list(pdfrender.render_pages(data, **kwargs))

    def test_pages_are_numbered_one_based_and_stay_in_document_order(self):
        pages = self.render(minimal_pdf(pages=3))
        self.assertEqual([page.number for page in pages], [1, 2, 3])

    def test_the_declared_page_count_is_read_from_the_document(self):
        self.assertEqual(pdfrender.page_count(minimal_pdf(pages=5)), 5)

    def test_every_page_says_which_renderer_drew_it(self):
        """Provenance comes from the renderer, so a label cannot misname it."""
        for page in self.render(minimal_pdf(pages=2)):
            self.assertEqual(page.renderer, pdfrender.PDFIUM)

    def test_the_output_is_one_deterministic_media_type(self):
        page, = self.render(minimal_pdf())
        self.assertEqual(page.media_type, "image/png")
        self.assertTrue(page.image.startswith(b"\x89PNG\r\n\x1a\n"))

    def test_the_rendered_page_matches_its_reported_size(self):
        page, = self.render(minimal_pdf())
        image = read_png(page.image)
        self.assertEqual((image["width"], image["height"]),
                         (page.width, page.height))

    def test_the_long_edge_is_scaled_to_the_target(self):
        page, = self.render(minimal_pdf(width=612, height=792))
        self.assertEqual(max(page.width, page.height),
                         pdfrender.TARGET_LONG_EDGE)

    def test_a_blank_page_renders_white_not_black(self):
        """A transparent scan drawn onto an unfilled bitmap would come back
        black, and a black page reads as an unreadable one."""
        page, = self.render(minimal_pdf())
        rows = read_png(page.image)["rows"]
        self.assertEqual(set(rows[0][:30]), {255})
        self.assertEqual(set(rows[-1][-30:]), {255})

    def test_a_rotated_page_is_not_reoriented_twice(self):
        """PDFium's page size already applies /Rotate. Swapping the edges again
        — as the Quartz path must — would turn this page sideways."""
        upright, = self.render(minimal_pdf(width=612, height=792, rotate=0))
        sideways, = self.render(minimal_pdf(width=612, height=792, rotate=90))
        self.assertGreater(upright.height, upright.width, "portrait stays tall")
        self.assertGreater(sideways.width, sideways.height, "rotated is wide")
        self.assertAlmostEqual(upright.width, sideways.height, delta=2)
        self.assertAlmostEqual(upright.height, sideways.width, delta=2)

    def test_a_page_rotated_180_keeps_its_orientation(self):
        page, = self.render(minimal_pdf(width=612, height=792, rotate=180))
        self.assertGreater(page.height, page.width)

    def test_the_same_document_renders_to_the_same_bytes_twice(self):
        data = minimal_pdf(pages=2)
        self.assertEqual([p.image for p in self.render(data)],
                         [p.image for p in self.render(data)])

    # ---------------------------------------------------------------- bounds

    def test_a_pdf_over_the_size_ceiling_is_refused_before_opening(self):
        oversized = b"%PDF-1.4\n" + b"0" * pdfrender.MAX_PDF_BYTES
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(oversized)
        self.assertEqual(caught.exception.code, "too_large")

    def test_too_many_pages_is_refused_rather_than_silently_truncated(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(minimal_pdf(pages=3), max_pages=2)
        self.assertEqual(caught.exception.code, "too_many_pages")

    def test_the_module_ceiling_wins_over_a_larger_request(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(minimal_pdf(pages=pdfrender.MAX_PAGES + 1),
                        max_pages=1000)
        self.assertEqual(caught.exception.code, "too_many_pages")

    def test_a_page_over_the_pixel_ceiling_is_refused(self):
        with patch.object(pdfrender, "MAX_PIXELS_PER_PAGE", 100):
            with self.assertRaises(pdfrender.RenderError) as caught:
                self.render(minimal_pdf())
        self.assertEqual(caught.exception.code, "too_large")

    def test_an_oversized_encoded_page_is_refused(self):
        with patch.object(pdfrender, "MAX_IMAGE_BYTES", 10):
            with self.assertRaises(pdfrender.RenderError) as caught:
                self.render(minimal_pdf())
        self.assertEqual(caught.exception.code, "too_large")

    def test_a_page_with_no_usable_size_is_refused(self):
        """The guard itself. No document reaches it through PDFium, which
        substitutes a default page for a degenerate box — see the observation
        below — but the Quartz path reads the raw crop box and can."""
        for size in ((0, 0), (0, 792), (-1, 100)):
            with self.subTest(size=size):
                with self.assertRaises(pdfrender.RenderError) as caught:
                    pdfrender._target_size(*size)
                self.assertEqual(caught.exception.code, "malformed")

    def test_a_degenerate_media_box_is_normalised_by_the_engine(self):
        """Observed, not assumed: PDFium replaces a zero-size box with US
        Letter rather than reporting nothing. Recorded so the refusal above is
        not mistaken for the path a real document takes."""
        page, = self.render(minimal_pdf(width=0, height=0))
        self.assertGreater(page.width, 0)
        self.assertGreater(page.height, 0)

    # -------------------------------------------------------------- refusals

    def test_an_empty_document_is_refused(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(b"")
        self.assertEqual(caught.exception.code, "empty")

    def test_a_file_that_is_not_a_pdf_is_refused(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(b"this is not a pdf at all")
        self.assertEqual(caught.exception.code, "malformed")

    def test_a_truncated_pdf_is_refused_rather_than_partly_read(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            self.render(minimal_pdf()[:120])
        self.assertEqual(caught.exception.code, "malformed")

    def test_anything_that_is_not_bytes_is_refused(self):
        for value in ("%PDF-1.4", None, 42, ["%PDF"]):
            with self.subTest(value=value):
                with self.assertRaises(pdfrender.RenderError) as caught:
                    self.render(value)
                self.assertEqual(caught.exception.code, "unreadable")

    def test_cancellation_stops_between_pages(self):
        seen = []

        def stop():
            return len(seen) >= 2

        with self.assertRaises(pdfrender.RenderError) as caught:
            for page in pdfrender.render_pages(minimal_pdf(pages=4),
                                               should_cancel=stop,
                                               backend=pdfrender.PDFIUM):
                seen.append(page.number)
        self.assertEqual(caught.exception.code, "cancelled")
        self.assertEqual(seen, [1, 2])

    def test_a_render_that_overruns_its_deadline_stops(self):
        clock = iter([0.0, 0.0, 10_000.0, 10_000.0])
        with patch.object(pdfrender.time, "monotonic",
                          side_effect=lambda: next(clock, 10_000.0)):
            with self.assertRaises(pdfrender.RenderError) as caught:
                self.render(minimal_pdf(pages=3), deadline_seconds=1.0)
        self.assertEqual(caught.exception.code, "timeout")

    def test_nothing_is_read_from_a_path_or_a_url(self):
        """The renderer is only ever handed bytes, so a crafted document cannot
        make it open a local or remote file."""
        with self.assertRaises(pdfrender.RenderError):
            self.render(str(SCAN_FIXTURE))


class EncryptedDocuments(unittest.TestCase):
    """Password classification, through an injected PDFium.

    A real encrypted fixture is not committed, so this proves the mapping from
    PDFium's error code to Refinix's refusal — code, not prose, because matching
    English would stop being true the first time that prose changed. Source-
    tested: it is not evidence about a real encrypted file.
    """

    def fake_pdfium(self, code):
        class FakeError(RuntimeError):
            def __init__(self, message, err_code=None):
                super().__init__(message)
                self.err_code = err_code

        class Module:
            PdfiumError = FakeError

            @staticmethod
            def PdfDocument(_data):
                raise FakeError("Failed to load document.", code)

        class Raw:
            FPDF_ERR_PASSWORD = 4
            FPDF_ERR_SECURITY = 5
            FPDF_ERR_FORMAT = 3

        return Module, Raw

    def render(self, code):
        module, raw = self.fake_pdfium(code)
        with patch.object(pdfrender, "_pdfium", return_value=(module, raw)):
            with self.assertRaises(pdfrender.RenderError) as caught:
                list(pdfrender.render_pages(minimal_pdf(),
                                            backend=pdfrender.PDFIUM))
        return caught.exception

    def test_a_password_protected_pdf_is_refused_as_encrypted(self):
        error = self.render(4)
        self.assertEqual(error.code, "encrypted")
        self.assertIn("does not unlock", str(error))

    def test_an_unsupported_security_handler_is_refused_as_encrypted(self):
        self.assertEqual(self.render(5).code, "encrypted")

    def test_any_other_load_failure_is_malformed_not_encrypted(self):
        self.assertEqual(self.render(3).code, "malformed")

    def test_an_unreported_error_code_is_malformed_not_assumed_unlocked(self):
        self.assertEqual(self.render(None).code, "malformed")



class TextLayer(unittest.TestCase):
    """Reading a PDF's own text, which needs no model and draws no page."""

    def setUp(self):
        state = pdfrender._pdfium_probe()
        if not state["available"]:
            self.skipTest(state["detail"])

    def test_each_page_keeps_its_number_and_its_own_text(self):
        pages = pdfrender.text_pages(text_pdf(["Pump vibration 7.9 mm/s",
                                               "Gauge reading illegible"]))
        self.assertEqual([page.number for page in pages], [1, 2])
        self.assertIn("Pump vibration 7.9 mm/s", pages[0].text)
        self.assertIn("Gauge reading illegible", pages[1].text)
        self.assertFalse(any(page.truncated for page in pages))

    def test_a_page_without_a_text_layer_comes_back_empty(self):
        pages = pdfrender.text_pages(text_pdf(["Readable", None]))
        self.assertEqual(pages[1].text, "")
        self.assertEqual(pages[1].chars, 0)

    def test_no_page_is_rendered_to_read_its_text(self):
        with patch.object(pdfrender, "_pdfium_page",
                          side_effect=AssertionError("rendered")), \
                patch.object(pdfrender, "encode_png",
                             side_effect=AssertionError("encoded")):
            pages = pdfrender.text_pages(text_pdf(["Only text"]))
        self.assertIn("Only text", pages[0].text)

    def test_the_page_limit_refuses_before_any_page_is_read(self):
        with patch.object(pdfrender, "_pdfium_page_text",
                          side_effect=AssertionError("read a page")):
            with self.assertRaises(pdfrender.RenderError) as caught:
                pdfrender.text_pages(minimal_pdf(pages=pdfrender.MAX_PAGES + 1))
        self.assertEqual(caught.exception.code, "too_many_pages")

    def test_a_page_over_the_ceiling_is_marked_partial_not_silently_cut(self):
        with patch.object(pdfrender, "MAX_TEXT_CHARS_PER_PAGE", 10):
            page, = pdfrender.text_pages(text_pdf(["abcdefghijklmnopqrstuvwxyz"]))
        self.assertTrue(page.truncated)
        self.assertGreater(page.chars, 10)
        self.assertLessEqual(len(page.text), 10)

    def test_truncated_and_garbage_input_is_malformed(self):
        whole = text_pdf(["Readable"])
        for data in (whole[: len(whole) // 3], b"%PDF-1.4 not really"):
            with self.subTest(size=len(data)):
                with self.assertRaises(pdfrender.RenderError) as caught:
                    pdfrender.text_pages(data)
                self.assertEqual(caught.exception.code, "malformed")

    def test_oversized_input_is_refused_before_it_is_opened(self):
        with patch.object(pdfrender, "_pdfium",
                          side_effect=AssertionError("opened")):
            with self.assertRaises(pdfrender.RenderError) as caught:
                pdfrender.text_pages(b"%PDF-1.4\n" + b"0" * pdfrender.MAX_PDF_BYTES)
        self.assertEqual(caught.exception.code, "too_large")

    def test_cancellation_stops_between_pages(self):
        with self.assertRaises(pdfrender.RenderError) as caught:
            pdfrender.text_pages(text_pdf(["one", "two"]), should_cancel=lambda: True)
        self.assertEqual(caught.exception.code, "cancelled")

    def test_the_deadline_stops_between_pages(self):
        ticks = iter([0.0, 10_000.0, 10_000.0, 10_000.0])
        with patch.object(pdfrender.time, "monotonic", lambda: next(ticks)):
            with self.assertRaises(pdfrender.RenderError) as caught:
                pdfrender.text_pages(text_pdf(["one", "two"]))
        self.assertEqual(caught.exception.code, "timeout")

    def test_an_encrypted_pdf_is_refused_as_encrypted(self):
        module, raw = EncryptedDocuments().fake_pdfium(4)
        with patch.object(pdfrender, "_pdfium", return_value=(module, raw)):
            with self.assertRaises(pdfrender.RenderError) as caught:
                pdfrender.text_pages(minimal_pdf())
        self.assertEqual(caught.exception.code, "encrypted")

    def test_the_probe_names_what_is_missing(self):
        absent = pdfrender.RenderError("no_renderer", "absent here")
        with patch.object(pdfrender, "_pdfium", side_effect=absent):
            state = pdfrender.text_probe()
        self.assertFalse(state["available"])
        self.assertIn("absent here", state["detail"])
        self.assertTrue(pdfrender.text_probe()["available"])

class BackendSelection(unittest.TestCase):
    def test_the_portable_backend_is_first_in_preference_order(self):
        self.assertEqual(pdfrender.BACKEND_ORDER[0], pdfrender.PDFIUM)

    def test_the_probe_reports_every_backend_it_found(self):
        state = pdfrender.probe()
        self.assertIn("backends", state)
        if state["available"]:
            self.assertIn(state["module"], state["backends"])

    def test_an_unavailable_probe_explains_every_backend(self):
        absent = pdfrender.RenderError("no_renderer", "absent here")
        with patch.object(pdfrender, "_pdfium", side_effect=absent), \
                patch.object(pdfrender, "_quartz", side_effect=absent):
            state = pdfrender.probe()
        self.assertFalse(state["available"])
        self.assertIsNone(state["module"])
        self.assertIn("cannot render PDF pages", state["detail"])

    def test_each_backend_probe_names_itself(self):
        for state in pdfrender.backends():
            with self.subTest(module=state["module"]):
                self.assertIn(state["module"],
                              (pdfrender.PDFIUM, pdfrender.QUARTZ))
                self.assertTrue(state["detail"].strip())


class RealScan(unittest.TestCase):
    """The C07 scan through the selected renderer, on this computer."""

    def setUp(self):
        if not SCAN_FIXTURE.exists():
            self.skipTest("the C07 scan fixture is not present")
        if not pdfrender.available():
            self.skipTest("no PDF renderer is installed in this environment")
        self.data = SCAN_FIXTURE.read_bytes()

    def test_the_scan_renders_three_legible_png_pages(self):
        self.assertEqual(pdfrender.page_count(self.data), 3)
        pages = list(pdfrender.render_pages(self.data))
        self.assertEqual([page.number for page in pages], [1, 2, 3])
        for page in pages:
            image = read_png(page.image)
            self.assertEqual((image["width"], image["height"]),
                             (page.width, page.height))
            self.assertGreater(len(page.image), 1000)

    def test_the_scan_is_not_rendered_blank(self):
        """A page of solid white would pass a size check and read as nothing."""
        page = next(iter(pdfrender.render_pages(self.data)))
        shades = {byte for row in read_png(page.image)["rows"] for byte in row}
        self.assertGreater(len(shades), 1, "the page has no ink at all")

    @unittest.skipUnless(pdfrender._quartz_probe()["available"],
                         "the Quartz fallback is not installed here")
    def test_both_backends_agree_about_the_same_scan(self):
        """A cross-check only a computer with both renderers can make. Pixels
        differ between rasterisers; the page count and geometry must not."""
        portable = list(pdfrender.render_pages(self.data,
                                               backend=pdfrender.PDFIUM))
        quartz = list(pdfrender.render_pages(self.data,
                                             backend=pdfrender.QUARTZ))
        self.assertEqual([p.number for p in portable], [p.number for p in quartz])
        for left, right in zip(portable, quartz):
            self.assertAlmostEqual(left.width, right.width, delta=2)
            self.assertAlmostEqual(left.height, right.height, delta=2)
            self.assertEqual(left.media_type, right.media_type)
        self.assertEqual([p.renderer for p in portable],
                         [pdfrender.PDFIUM] * len(portable))
        self.assertEqual([p.renderer for p in quartz],
                         [pdfrender.QUARTZ] * len(quartz))


if __name__ == "__main__":
    unittest.main()
